name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "main" ]

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install & Build (Vite)
        working-directory: web
        run: |
          npm ci
          npm run build

      - name: Install SWA CLI
        run: npm i -g @azure/static-web-apps-cli

      - name: Deploy with SWA CLI
        env:
          SWA_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_COAST_05465D903 }}
        run: |
          swa deploy ./web/dist --env production --deployment-token "$SWA_TOKEN"

  close_pr:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close PR env
        env:
          SWA_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_COAST_05465D903 }}
        run: echo "Closing PR env is not needed for CLI deploys."
